export const RECEIVE_CATEGORIES = "RECEIVE_CATEGORIES";
export const RECEIVE_ALL_COMMENTS = "RECEIVE_ALL_COMMENTS";
export const RECEIVE_COMMENT = "RECEIVE_COMMENT";
export const RECEIVE_ALL_POSTS = "RECEIVE_ALL_POSTS";
export const RECEIVE_CATEGORY_POSTS = "RECEIVE_CATEGORY_POSTS";
export const RECEIVE_POST = "RECEIVE_POST";